services:
  - type: web
    name: nova-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: nova-postgres
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ISSUER
        value: NovaAPI
      - key: JWT_AUDIENCE
        value: NovaClients

databases:
  - name: nova-postgres
    plan: starter